name: Build Windows Image

on:
  push:
    branches: [ ci/cd ]
    paths:
      - 'Dockerfile.windows'
  pull_request:
    branches: [ ci/cd ]
    paths:
      - 'Dockerfile.windows'

jobs:
  build-windows-image:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: set lowercase repository name
        shell: pwsh
        run: |
          $repo = "${{ github.repository }}".ToLower()
          Add-Content -Path $env:GITHUB_ENV -Value "REPO_NAME_LOWER=$repo"
      - name: build & push windows image
        shell: pwsh
        run: |
          $img = "ghcr.io/${{ env.REPO_NAME_LOWER }}/ci-image-windows:latest"
          docker build -f Dockerfile.windows -t ghcr.io/${{ env.REPO_NAME_LOWER }}/ci-image-windows:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ env.REPO_NAME_LOWER }}/ci-image-windows:latest
