name: Build Windows Image

on:
  push:
    branches: [ ci/cd ]
    paths:
      - 'Dockerfile.windows'
  pull_request:
    branches: [ ci/cd ]
    paths:
      - 'Dockerfile.windows'

jobs:
  build-windows-image:
    permissions: write-all
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Lowercase Repository Name
        id: repo_name
        run: echo "REPO_NAME_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_ENV"
      - name: build & push windows image
        run: |
          # build already tagged for ghcr
          docker build -f Dockerfile.windows -t ghcr.io/${{ env.REPO_NAME_LOWER }}/ci-image-windows:latest .
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ env.REPO_NAME_LOWER }}/ci-image-windows:latest
