name: precache-dependencies

on:
  push:
    branches:
      - main

jobs:
  cache-windows-deps:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: cache vcpkg
        id: cache-vcpkg
        uses: actions/cache@v3
        with:
          path: c:/vcpkg/installed/x64-windows
          key: windows-vcpkg-installed
          restore-keys: |
            windows-vcpkg-installed

      - name: install vcpkg deps
        if: steps.cache-vcpkg.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          & c:/vcpkg/vcpkg.exe install opencv4:x64-windows

      - name: cache tensorflow c api
        id: cache-tf
        uses: actions/cache@v3
        with:
          path: c:/tensorflow
          key: windows-tf-capi-2.18.1
          restore-keys: |
            windows-tf-capi-2.18.1

      - name: download tensorflow c api
        if: steps.cache-tf.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $url = "https://storage.googleapis.com/tensorflow/versions/2.18.1/libtensorflow-cpu-windows-x86_64.zip"
          Invoke-WebRequest $url -OutFile tf.zip
          Expand-Archive tf.zip -DestinationPath c:/tensorflow
          Remove-Item tf.zip

      - name: cache libtorch c api
        id: cache-libtorch
        uses: actions/cache@v3
        with:
          path: c:/pytorch
          key: windows-torch-capi-2.7.0
          restore-keys: |
            windows-torch-capi-2.7.0

      - name: download libtorch c api
        if: steps.cache-libtorch.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          $url = "https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-2.7.0%2Bcpu.zip"
          Invoke-WebRequest $url -OutFile torch.zip
          Expand-Archive torch.zip -DestinationPath c:/pytorch
          Remove-Item torch.zip